###############################################################################
# Monitoring: log group with retention, SNS email topic, CloudWatch alarms.
###############################################################################

# Container stdout (via the Docker awslogs driver) and system logs land here.
# Retention is explicit - logs are not kept forever.
resource "aws_cloudwatch_log_group" "app" {
  name              = "/aws/ec2/${var.name}/app"
  retention_in_days = var.log_retention_days

  tags = merge(var.tags, { Name = "${var.name}-app-logs" })
}

###############################################################################
# Notification channel
###############################################################################

# Customer-managed KMS key so the SNS topic is encrypted at rest. The AWS-managed
# alias/aws/sns key cannot be used here: its key policy does not grant the
# CloudWatch service principal permission to generate a data key, so alarms
# would silently fail to publish. The policy below grants exactly that.
resource "aws_kms_key" "sns" {
  count = var.enable_sns_encryption ? 1 : 0

  description             = "Encrypts the ${var.name} SNS alarm topic at rest."
  enable_key_rotation     = true
  deletion_window_in_days = 7

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        # Without this the key becomes unmanageable by anyone in the account.
        Sid       = "AllowAccountAdministration"
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" }
        Action    = "kms:*"
        Resource  = "*"
      },
      {
        # Lets CloudWatch alarms encrypt the message they publish to the topic.
        Sid       = "AllowCloudWatchAlarmsToUseTheKey"
        Effect    = "Allow"
        Principal = { Service = "cloudwatch.amazonaws.com" }
        Action = [
          "kms:GenerateDataKey*",
          "kms:Decrypt",
        ]
        Resource = "*"
      },
    ]
  })

  tags = merge(var.tags, { Name = "${var.name}-sns-key" })
}

resource "aws_kms_alias" "sns" {
  count = var.enable_sns_encryption ? 1 : 0

  name          = "alias/${var.name}-sns"
  target_key_id = aws_kms_key.sns[0].key_id
}

resource "aws_sns_topic" "alarms" {
  name              = "${var.name}-alarms"
  kms_master_key_id = var.enable_sns_encryption ? aws_kms_key.sns[0].arn : null

  tags = merge(var.tags, { Name = "${var.name}-alarms" })
}

# The subscription is created in "pending confirmation" state; AWS emails a
# confirmation link that has to be clicked once. Terraform cannot confirm it.
resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.alarms.arn
  protocol  = "email"
  endpoint  = var.alarm_email
}

resource "aws_sns_topic_policy" "alarms" {
  arn = aws_sns_topic.alarms.arn

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowCloudWatchAlarmsToPublish"
      Effect    = "Allow"
      Principal = { Service = "cloudwatch.amazonaws.com" }
      Action    = "sns:Publish"
      Resource  = aws_sns_topic.alarms.arn
    }]
  })
}

###############################################################################
# Alarms
###############################################################################

# 5XX responses returned by the application targets. This is the alarm
# demonstrated in docs/ALARM-DEMO.md by calling GET /simulate/500 in a loop.
resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  alarm_name          = "${var.name}-target-5xx"
  alarm_description   = "Application targets returned ${var.alb_5xx_threshold} or more 5XX responses in one minute."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 60
  evaluation_periods  = 1
  threshold           = var.alb_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = var.target_group_arn_suffix
  }

  alarm_actions = [aws_sns_topic.alarms.arn]
  ok_actions    = [aws_sns_topic.alarms.arn]

  tags = var.tags
}

# 5XX generated by the load balancer itself (no healthy target, timeouts).
resource "aws_cloudwatch_metric_alarm" "elb_5xx" {
  alarm_name          = "${var.name}-elb-5xx"
  alarm_description   = "The load balancer itself returned 5XX responses (no healthy targets or upstream timeouts)."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  period              = 60
  evaluation_periods  = 1
  threshold           = var.alb_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = [aws_sns_topic.alarms.arn]
  ok_actions    = [aws_sns_topic.alarms.arn]

  tags = var.tags
}

# Any target failing its /health check for two consecutive minutes.
resource "aws_cloudwatch_metric_alarm" "unhealthy_hosts" {
  alarm_name          = "${var.name}-unhealthy-hosts"
  alarm_description   = "One or more targets are failing the /health check."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "UnHealthyHostCount"
  statistic           = "Maximum"
  period              = 60
  evaluation_periods  = 2
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = var.target_group_arn_suffix
  }

  alarm_actions = [aws_sns_topic.alarms.arn]
  ok_actions    = [aws_sns_topic.alarms.arn]

  tags = var.tags
}

# Fewer healthy targets than the ASG minimum - capacity has degraded.
resource "aws_cloudwatch_metric_alarm" "healthy_hosts" {
  alarm_name          = "${var.name}-healthy-hosts-low"
  alarm_description   = "Fewer than two healthy targets are registered with the load balancer."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HealthyHostCount"
  statistic           = "Minimum"
  period              = 60
  evaluation_periods  = 3
  threshold           = 2
  comparison_operator = "LessThanThreshold"
  # "missing" rather than "breaching": the metric has no datapoints until the
  # first targets register, and a false alarm email on every apply is noise.
  treat_missing_data = "missing"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
    TargetGroup  = var.target_group_arn_suffix
  }

  alarm_actions = [aws_sns_topic.alarms.arn]

  tags = var.tags
}

###############################################################################
# Dashboard
###############################################################################

resource "aws_cloudwatch_dashboard" "this" {
  dashboard_name = "${var.name}-overview"

  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6
        properties = {
          title  = "ALB requests and errors"
          region = data.aws_region.current.name
          view   = "timeSeries"
          metrics = [
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", var.alb_arn_suffix],
            [".", "HTTPCode_Target_5XX_Count", ".", ".", { yAxis = "right" }],
            [".", "HTTPCode_ELB_5XX_Count", ".", ".", { yAxis = "right" }],
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 0
        width  = 12
        height = 6
        properties = {
          title  = "Target health"
          region = data.aws_region.current.name
          view   = "timeSeries"
          metrics = [
            ["AWS/ApplicationELB", "HealthyHostCount", "LoadBalancer", var.alb_arn_suffix, "TargetGroup", var.target_group_arn_suffix],
            [".", "UnHealthyHostCount", ".", ".", ".", "."],
          ]
        }
      },
    ]
  })
}

data "aws_region" "current" {}
data "aws_caller_identity" "current" {}
